# Generated by Django 5.0.6 on 2024-07-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0002_remove_producto_imagen_url_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
